# Person detection settings
detection_interval: 75

# Gesture recognition settings
gesture_class_num: 5
gesture_prediction_interval: 1
no_gesture_thres: 0.65

# Local model paths
# detection_model_name: "./data/models/PersonDetectionWeights/person_detection_ctu_v2.pb"
detection_model_name: "./data/models/PersonDetectionWeights/frozen_inference_graph_webcam.pb"
tracking_model_name: "./data/models/PersonDetectionWeights/SiamRPNOTB.model"
pose2d_model_weights_path: "./data/models/HumanPoseWeights/model_2d.pth"
gesture_model_5g_weights_path: "./data/models/GestureWeights/mixed_5g_ref.pth"
gesture_model_6g_weights_path: "./data/models/GestureWeights/mixed_6g_ref.pth"

# Model URLs for downloading
gdrive_url_detection: "https://drive.google.com/file/d/1icBa8Ou7x9cswXDkvv0sEv4p0vchLICc/view?usp=sharing"
gdrive_url_tracking: "https://drive.google.com/file/d/1ROv9gtA2ffIvL7eFn83Fwea7VIOCmAUT/view?usp=sharing"
gdrive_url_pose2d: "https://drive.google.com/file/d/1G0K2xuH7P6x7o-UjZwdKrE4G2KcnNoKL/view?usp=sharing"
gdrive_url_gesture_5classes: "https://drive.google.com/file/d/1oZgMVwUBGrVzZY0gzvvX9yK8W1vCEnvg/view?usp=sharing"
gdrive_url_gesture_6classes: "https://drive.google.com/file/d/1Mq_1cUUN1SjELYLrCSzHka1rMvR4goaL/view?usp=sharing"
